// Mock data for NZHA platform — Saudi Arabia

export const SAUDI_CITIES = [
  'الرياض', 'جدة', 'مكة المكرمة', 'المدينة المنورة', 'الدمام',
  'الخبر', 'الظهران', 'أبها', 'الطائف', 'تبوك',
  'الأحساء', 'نجران', 'جازان', 'ينبع', 'حائل',
  'القصيم', 'القطيف', 'ضباء', 'الباحة', 'شرورة'
];

export const AMENITIES = [
  { key: 'pool', label: 'مسبح', icon: 'fa-solid fa-person-swimming' },
  { key: 'bbq', label: 'شواء', icon: 'fa-solid fa-fire-burner' },
  { key: 'cinema', label: 'سينما', icon: 'fa-solid fa-clapperboard' },
  { key: 'gym', label: 'صالة رياضية', icon: 'fa-solid fa-dumbbell' },
  { key: 'wifi', label: 'واي فاي', icon: 'fa-solid fa-wifi' },
  { key: 'parking', label: 'مواقف سيارات', icon: 'fa-solid fa-square-parking' },
  { key: 'jacuzzi', label: 'جاكوزي', icon: 'fa-solid fa-hot-tub-person' },
  { key: 'playground', label: 'ملعب أطفال', icon: 'fa-solid fa-child-reaching' },
  { key: 'garden', label: 'حديقة', icon: 'fa-solid fa-leaf' },
  { key: 'kitchen', label: 'مطبخ مجهز', icon: 'fa-solid fa-kitchen-set' },
  { key: 'ac', label: 'تكييف مركزي', icon: 'fa-solid fa-snowflake' },
  { key: 'security', label: 'حراسة أمنية', icon: 'fa-solid fa-shield-halved' },
];

export const SERVICE_CATEGORIES = [
  { key: 'photography', label: 'تصوير', icon: 'fa-solid fa-camera' },
  { key: 'decoration', label: 'ديكور وزينة', icon: 'fa-solid fa-wand-magic-sparkles' },
  { key: 'beverage', label: 'ضيافة ومشروبات', icon: 'fa-solid fa-mug-hot' },
  { key: 'sound', label: 'صوتيات وإضاءة', icon: 'fa-solid fa-music' },
  { key: 'catering', label: 'بوفيه وطعام', icon: 'fa-solid fa-utensils' },
];

export const PROPERTIES = [
  {
    id: 1,
    name: 'منتجع النخيل الفاخر',
    type: 'resort',
    typeLabel: 'منتجع',
    city: 'الرياض',
    description: 'منتجع فاخر يجمع بين الأصالة العربية والتصميم العصري. يضم مسبحاً خارجياً بانورامياً ومرافق ترفيهية متكاملة وسط أجواء هادئة تمنحك تجربة لا تُنسى مع عائلتك أو أصدقائك.',
    bedrooms: 6,
    bathrooms: 5,
    maxCapacity: 20,
    basePrice: 1800,
    cleaningFee: 200,
    weekendPrice: 2200,
    minStay: 2,
    rating: 4.9,
    reviewCount: 124,
    images: ['/resort_hero.png', '/chalet_pool.png', '/resort_interior.png', '/chalet_bbq.png', '/resort_bedroom.png'],
    amenities: ['pool', 'bbq', 'cinema', 'gym', 'wifi', 'parking', 'jacuzzi', 'kitchen', 'ac', 'security'],
    rules: { smoking: false, pets: false, parties: true, checkIn: '14:00', checkOut: '12:00' },
    securityDeposit: 1000,
    isInstantBook: true,
    isFeatured: true,
    host: { name: 'عبدالله المنيع', photo: null, responseRate: 98, memberSince: '2022' },
    lat: 24.7136, lng: 46.6753,
    status: 'active',
  },
  {
    id: 2,
    name: 'شاليه الواحة الهادئة',
    type: 'chalet',
    typeLabel: 'شاليه',
    city: 'جدة',
    description: 'شاليه راقٍ على ساحل جدة يوفر إطلالات رائعة على البحر الأحمر مع مرافق خاصة كاملة للاسترخاء والاستمتاع.',
    bedrooms: 4,
    bathrooms: 3,
    maxCapacity: 14,
    basePrice: 1200,
    cleaningFee: 150,
    weekendPrice: 1500,
    minStay: 1,
    rating: 4.7,
    reviewCount: 89,
    images: ['/chalet_pool.png', '/resort_interior.png', '/resort_hero.png', '/chalet_bbq.png', '/resort_bedroom.png'],
    amenities: ['pool', 'bbq', 'wifi', 'parking', 'kitchen', 'ac', 'garden'],
    rules: { smoking: false, pets: false, parties: false, checkIn: '15:00', checkOut: '11:00' },
    securityDeposit: 800,
    isInstantBook: false,
    isFeatured: true,
    host: { name: 'نورة العتيبي', photo: null, responseRate: 94, memberSince: '2023' },
    lat: 21.5433, lng: 39.1728,
    status: 'active',
  },
  {
    id: 3,
    name: 'فيلا الجبل الأخضر',
    type: 'vacation_rental',
    typeLabel: 'فيلا',
    city: 'أبها',
    description: 'فيلا فاخرة في قلب أبها وسط مناخ معتدل وطبيعة خلابة. مثالية لمن يبحث عن الهروب من حرارة الصيف في أجواء مرتفعات عسير.',
    bedrooms: 5,
    bathrooms: 4,
    maxCapacity: 16,
    basePrice: 900,
    cleaningFee: 100,
    weekendPrice: 1100,
    minStay: 2,
    rating: 4.8,
    reviewCount: 67,
    images: ['/resort_interior.png', '/resort_hero.png', '/chalet_pool.png', '/resort_bedroom.png', '/chalet_bbq.png'],
    amenities: ['bbq', 'wifi', 'parking', 'kitchen', 'ac', 'garden', 'playground'],
    rules: { smoking: false, pets: true, parties: true, checkIn: '13:00', checkOut: '12:00' },
    securityDeposit: 500,
    isInstantBook: true,
    isFeatured: false,
    host: { name: 'محمد القحطاني', photo: null, responseRate: 90, memberSince: '2021' },
    lat: 18.2164, lng: 42.5053,
    status: 'active',
  },
  {
    id: 4,
    name: 'منتجع اللؤلؤة الزرقاء',
    type: 'resort',
    typeLabel: 'منتجع',
    city: 'الدمام',
    description: 'منتجع ساحلي استثنائي على الخليج العربي يضم مسبحين وملاعب رياضية، مثالي للعائلات والمجموعات.',
    bedrooms: 8,
    bathrooms: 6,
    maxCapacity: 30,
    basePrice: 2500,
    cleaningFee: 300,
    weekendPrice: 3000,
    minStay: 2,
    rating: 4.6,
    reviewCount: 212,
    images: ['/chalet_bbq.png', '/chalet_pool.png', '/resort_hero.png', '/resort_interior.png', '/resort_bedroom.png'],
    amenities: ['pool', 'bbq', 'cinema', 'gym', 'wifi', 'parking', 'jacuzzi', 'playground', 'security'],
    rules: { smoking: false, pets: false, parties: true, checkIn: '14:00', checkOut: '12:00' },
    securityDeposit: 2000,
    isInstantBook: false,
    isFeatured: true,
    host: { name: 'سلطان الغامدي', photo: null, responseRate: 96, memberSince: '2020' },
    lat: 26.4207, lng: 50.0888,
    status: 'active',
  },
  {
    id: 5,
    name: 'شاليه الرمال الذهبية',
    type: 'chalet',
    typeLabel: 'شاليه',
    city: 'الطائف',
    description: 'شاليه مميز وسط مزارع الورد الطائفي العريقة مع مناخ لطيف طوال السنة وإطلالات طبيعية ساحرة.',
    bedrooms: 3,
    bathrooms: 2,
    maxCapacity: 10,
    basePrice: 650,
    cleaningFee: 80,
    weekendPrice: 800,
    minStay: 1,
    rating: 4.5,
    reviewCount: 45,
    images: ['/resort_bedroom.png', '/chalet_pool.png', '/resort_hero.png', '/chalet_bbq.png', '/resort_interior.png'],
    amenities: ['bbq', 'wifi', 'parking', 'kitchen', 'ac', 'garden'],
    rules: { smoking: false, pets: false, parties: false, checkIn: '15:00', checkOut: '11:00' },
    securityDeposit: 300,
    isInstantBook: true,
    isFeatured: false,
    host: { name: 'أحمد الزهراني', photo: null, responseRate: 88, memberSince: '2023' },
    lat: 21.2703, lng: 40.4158,
    status: 'active',
  },
  {
    id: 6,
    name: 'استراحة النهر الفضي',
    type: 'vacation_rental',
    typeLabel: 'استراحة',
    city: 'الأحساء',
    description: 'استراحة عائلية فاخرة في واحة الأحساء السياحية، تجمع بين الطابع البيئي والخدمات الحديثة.',
    bedrooms: 5,
    bathrooms: 3,
    maxCapacity: 18,
    basePrice: 800,
    cleaningFee: 100,
    weekendPrice: 950,
    minStay: 2,
    rating: 4.7,
    reviewCount: 38,
    images: ['/chalet_pool.png', '/resort_bedroom.png', '/chalet_bbq.png', '/resort_interior.png', '/resort_hero.png'],
    amenities: ['pool', 'bbq', 'wifi', 'parking', 'kitchen', 'ac', 'garden', 'playground'],
    rules: { smoking: false, pets: true, parties: true, checkIn: '14:00', checkOut: '12:00' },
    securityDeposit: 600,
    isInstantBook: true,
    isFeatured: false,
    host: { name: 'فاطمة الدوسري', photo: null, responseRate: 92, memberSince: '2022' },
    lat: 25.3829, lng: 49.5858,
    status: 'active',
  },
];

export const SERVICE_PACKAGES = [
  {
    id: 1,
    name: 'باقة التصوير الاحترافي',
    category: 'photography',
    categoryLabel: 'تصوير',
    providerId: 1,
    providerName: 'استوديو الذكريات',
    description: 'تغطية كاملة للفعالية مع مصور محترف وتسليم الصور معدلة خلال 48 ساعة.',
    basePrice: 1500,
    cities: ['الرياض', 'جدة', 'الدمام'],
    images: [],
    rating: 4.8,
    addons: [
      { id: 1, name: 'تصوير فيديو', priceDelta: 800 },
      { id: 2, name: 'بوم فوتو فريم', priceDelta: 300 },
      { id: 3, name: 'طباعة داخل الفعالية', priceDelta: 500 },
    ],
  },
  {
    id: 2,
    name: 'باقة الديكور الاحتفالي',
    category: 'decoration',
    categoryLabel: 'ديكور وزينة',
    providerId: 2,
    providerName: 'لمسة فرح',
    description: 'زينة وديكور احترافي للفعاليات والمناسبات مع فريق متخصص وأحدث الإكسسوارات.',
    basePrice: 1200,
    cities: ['الرياض', 'جدة', 'الطائف', 'الدمام'],
    images: [],
    rating: 4.9,
    addons: [
      { id: 4, name: 'طاولة الحلويات', priceDelta: 400 },
      { id: 5, name: 'نقش حناء', priceDelta: 350 },
      { id: 6, name: 'باقة الورود', priceDelta: 250 },
    ],
  },
  {
    id: 3,
    name: 'باقة الضيافة العربية',
    category: 'beverage',
    categoryLabel: 'ضيافة',
    providerId: 3,
    providerName: 'أرض القهوة',
    description: 'قهوة عربية وتمور وعصائر طازجة يقدمها فريق ضيافة احترافي طوال مدة الفعالية.',
    basePrice: 800,
    cities: ['جميع المدن السعودية'],
    images: [],
    rating: 4.7,
    addons: [
      { id: 7, name: 'بوفيه حلويات', priceDelta: 600 },
      { id: 8, name: 'آيس كريم ستاند', priceDelta: 400 },
    ],
  },
  {
    id: 4,
    name: 'باقة الصوتيات والإضاءة',
    category: 'sound',
    categoryLabel: 'صوتيات',
    providerId: 4,
    providerName: 'صوت الاحتفال',
    description: 'نظام صوت متكامل وإضاءة فنية مع مهندس صوت طوال الفعالية.',
    basePrice: 2000,
    cities: ['الرياض', 'جدة', 'الدمام', 'أبها'],
    images: [],
    rating: 4.6,
    addons: [
      { id: 9, name: 'شاشة LED عملاقة', priceDelta: 1500 },
      { id: 10, name: 'مدير حفل', priceDelta: 800 },
    ],
  },
];

export const REVIEWS = [
  {
    id: 1,
    bookingId: 1,
    propertyId: 1,
    reviewer: { name: 'خالد المطيري', initials: 'خ' },
    rating: 5,
    text: 'تجربة لا تُنسى! المنتجع نظيف للغاية والخدمة ممتازة. الموقع رائع والمرافق فوق التوقعات. سنعود حتماً.',
    date: '2026-01-15',
  },
  {
    id: 2,
    bookingId: 2,
    propertyId: 1,
    reviewer: { name: 'منى العسيري', initials: 'م' },
    rating: 5,
    text: 'مكان رائع جداً مناسب للعائلات. المسبح واسع والمطبخ مجهز بالكامل. الصاحب متجاوب وكريم.',
    date: '2026-01-22',
  },
  {
    id: 3,
    bookingId: 3,
    propertyId: 1,
    reviewer: { name: 'سعود البارقي', initials: 'س' },
    rating: 4,
    text: 'تجربة جميلة جداً. السعر مناسب لما يقدمه المكان من خدمات فاخرة. أنصح به بشدة.',
    date: '2026-02-01',
  },
];

export const MOCK_BOOKINGS = [
  {
    id: 'NZ-2026-001234',
    property: PROPERTIES[0],
    checkIn: '2026-03-10',
    checkOut: '2026-03-13',
    nights: 3,
    guests: 8,
    status: 'confirmed',
    baseAmount: 5400,
    cleaningFee: 200,
    serviceFee: 280,
    total: 5880,
    packages: [],
  },
  {
    id: 'NZ-2026-000891',
    property: PROPERTIES[1],
    checkIn: '2026-02-20',
    checkOut: '2026-02-22',
    nights: 2,
    guests: 4,
    status: 'completed',
    baseAmount: 2400,
    cleaningFee: 150,
    serviceFee: 128,
    total: 2678,
    packages: [SERVICE_PACKAGES[0]],
  },
  {
    id: 'NZ-2026-000567',
    property: PROPERTIES[4],
    checkIn: '2026-01-15',
    checkOut: '2026-01-16',
    nights: 1,
    guests: 2,
    status: 'cancelled',
    baseAmount: 650,
    cleaningFee: 80,
    serviceFee: 37,
    total: 767,
    packages: [],
  },
];

export const ADMIN_STATS = {
  totalBookings: { today: 47, month: 1284, allTime: 18920 },
  gmv: { month: 2480000, allTime: 38600000 },
  platformRevenue: { month: 248000, allTime: 3860000 },
  activeProperties: 342,
  activeHosts: 210,
  activeGuests: 8745,
  pendingProperties: 12,
  openDisputes: 5,
};

export const HOST_STATS = {
  confirmedBookings: { month: 28, allTime: 342 },
  revenue: { platform: 48600, external: 12400, total: 61000 },
  occupancyRate: 74,
  averageRating: 4.8,
  pendingRequests: 3,
  unreadMessages: 7,
};

export const formatPrice = (price) => {
  return new Intl.NumberFormat('ar-SA', { style: 'currency', currency: 'SAR', maximumFractionDigits: 0 }).format(price);
};

export const formatDate = (dateStr) => {
  return new Date(dateStr).toLocaleDateString('ar-SA', { year: 'numeric', month: 'long', day: 'numeric' });
};

export const getStatusLabel = (status) => {
  const map = {
    confirmed: { label: 'مؤكد', class: 'badge-success' },
    pending: { label: 'قيد الانتظار', class: 'badge-warning' },
    completed: { label: 'مكتمل', class: 'badge-info' },
    cancelled: { label: 'ملغى', class: 'badge-danger' },
    active: { label: 'نشط', class: 'badge-success' },
    rejected: { label: 'مرفوض', class: 'badge-danger' },
    suspended: { label: 'موقوف', class: 'badge-warning' },
  };
  return map[status] || { label: status, class: 'badge-info' };
};
